### ISSUE TITLE
Errors in translation into Brazilian Portuguese

### ISSUE THREAD

**Issue by rodrigovet** [ingbrzy/MA-XML-10-BRAZILIAN#12]
EDIT: Correções de traduções para o Português brasileiro parece que foram abandonadas.
Não há nenhuma correção já fazem meses. 
Já reportei alguns erros e ninguém responde ou faz as correções necessárias.
EDIT: Fixes for translations into Brazilian Portuguese seem to have been abandoned.
There are no fixes for months now.
I've reported some errors and no one answers or makes the necessary corrections.

Algumas traduções de Português (Brasil) estão incorretas.
Existem alguns erros de tradução para o português brasileiro.
Percebi que há uma mistura na tradução do português / brasileiro com o português / de Portugal.
Eu postei alguns PrintScreens com alguns erros, mas ainda existem muitos para corrigir.
Principalmente no aplicativo Configurações e no FileExplorer.
Dispositivo: Xiaomi Redmi Note 4X (mido)
MIUI-WEEKLY-RELEASE / 8.10.11

Some Portuguese(Brazil) translations are incorrect.
There are quite a few translation errors for Brazilian Portuguese.
I noticed that there is a mixture in the translation of Portuguese / Brazilian with Portuguese / from Portugal.
I posted some PrintScreens with some errors, but there are many to fix it yet. Mainly in the Settings application and the FileExplorer.
Device: Xiaomi Redmi Note 4X(mido)
MIUI-WEEKLY-RELEASE / 8.10.11

**Comment by rodrigovet** [comment]
Some PrintScreens of translation errors:
![screenshot_2018-09-15-00-06-44-494_com android thememanager](https://user-images.githubusercontent.com/30162760/46576171-3c61f780-c99a-11e8-85ea-3e1ceb7f26ab.png)
![screenshot_2018-09-15-00-08-22-309_com miui securitycenter](https://user-images.githubusercontent.com/30162760/46576172-3c61f780-c99a-11e8-8caf-d061022ca7aa.png)
![screenshot_2018-09-15-00-13-40-969_com miui home](https://user-images.githubusercontent.com/30162760/46576174-3c61f780-c99a-11e8-9cfe-13ad46b16429.png)
![screenshot_2018-09-15-00-14-11-197_com miui home](https://user-images.githubusercontent.com/30162760/46576175-3c61f780-c99a-11e8-8aaf-77cdf09509ad.png)
![screenshot_2018-09-15-00-38-15-352_com miui home](https://user-images.githubusercontent.com/30162760/46576176-3cfa8e00-c99a-11e8-92ed-6dedc06414e6.png)
![screenshot_2018-09-15-03-30-37-973_com android fileexplorer](https://user-images.githubusercontent.com/30162760/46576177-3cfa8e00-c99a-11e8-8949-fb9bccf0c1b8.png)
![screenshot_2018-09-15-03-30-47-708_com android fileexplorer](https://user-images.githubusercontent.com/30162760/46576178-3cfa8e00-c99a-11e8-81a0-27084a55842e.png)
![screenshot_2018-10-06-19-14-20-511_com mfashiongallery emag](https://user-images.githubusercontent.com/30162760/46576361-1cccce00-c99e-11e8-8bea-a5c8651bb36c.png)
![screenshot_2018-10-06-19-15-58-937_com android settings](https://user-images.githubusercontent.com/30162760/46576362-1d656480-c99e-11e8-8522-a00ee1a3aeb4.png)
![screenshot_2018-10-06-19-13-27-297_com android settings](https://user-images.githubusercontent.com/30162760/46576363-1d656480-c99e-11e8-9075-54e04aa6076c.png)
![screenshot_2018-10-06-19-18-59-615_lockscreen](https://user-images.githubusercontent.com/30162760/46576364-1d656480-c99e-11e8-9c03-a1955b2f4f6b.png)
![screenshot_2018-10-06-19-18-47-166_lockscreen](https://user-images.githubusercontent.com/30162760/46576365-1d656480-c99e-11e8-9735-777dfcf9f36b.png)

**Comment by gugacavalieri** [comment]
created pull request https://github.com/ingbrzy/MA-XML-10-BRAZILIAN/pull/16 to fix some labels:

[PR#16](https://github.com/ingbrzy/MA-XML-10-BRAZILIAN/pull/16)

**Comment by rodrigovet** [comment]
![screenshot_2018-10-16-16-47-55-353_com android settings](https://user-images.githubusercontent.com/30162760/47059617-8e77f980-d1a0-11e8-9da6-4ede37dcafdd.png)
![screenshot_2018-10-16-16-36-16-663_com android settings](https://user-images.githubusercontent.com/30162760/47059618-8e77f980-d1a0-11e8-9a59-d4f103b388ca.png)

**Comment by rodrigovet** [comment]
![screenshot_2018-10-17-10-14-16-756_com android fileexplorer](https://user-images.githubusercontent.com/30162760/47090470-5e107980-d1f9-11e8-95c5-a488c5ac32a7.png)

**Comment by joaopr02** [comment]
Device: Redmi 6 Pro
MIUI Version: Stable 10.0.2.0
![screenshot_2018-10-18-06-56-17-427_com android settings](https://user-images.githubusercontent.com/44249272/47146900-66bd8a00-d2a3-11e8-964d-7f26994bf6e4.png)

**Comment by joaopr02** [comment]
For Portuguese Brazil language, the 4G icon is being showed as LTE.

**Comment by rodrigovet** [comment]
![img_20181123_020459](https://user-images.githubusercontent.com/30162760/48953209-2c8f7a00-ef2c-11e8-87b4-f22c7eb87ce8.jpg)

![img_20181123_020552](https://user-images.githubusercontent.com/30162760/48953214-34e7b500-ef2c-11e8-90e8-d175b133649c.jpg)

**Comment by joaopr02** [comment]
The LTE icon not the default icon in Brazil, the correct should be 4G.
![screenshot](https://user-images.githubusercontent.com/44249272/48956638-45535c00-ef3b-11e8-9d48-ca513033d576.png)

**Comment by rodrigovet** [comment]
![img_20181123_165102](https://user-images.githubusercontent.com/30162760/48957580-8bf78500-ef40-11e8-8b3b-a2afe880d5ef.jpg)

**Comment by rodrigovet** [comment]
![img_20181216_211426](https://user-images.githubusercontent.com/30162760/50060324-ac9aaf80-0179-11e9-84dd-cafbe35fa8c6.jpg)

**Comment by rodrigovet** [comment]
![img_20181216_211310](https://user-images.githubusercontent.com/30162760/50060334-be7c5280-0179-11e9-9b11-4e7737e96430.jpg)

**Comment by Feurrado** [comment]
Maioria dos erros traduzidos, somente alguns que não consegui localizar mas vou continuar tentando, obrigado por reportar ^^
