### ISSUE TITLE
Tradução incorreta

### ISSUE THREAD

**Issue by xZezao** [ingbrzy/MA-XML-10-BRAZILIAN#19]
Uma tradução equivocada na palavra que deveria ser "APAGAR" (em maiusculo, seguindo a palavra ao lado) e está "Eliminar" (em minusculo) que creio que seja PT-PT e não PT-BR

Outro problema é as palavras que não estão em concordancia, deveria seguir o padrão do titulo que é "senha" e não "palavra-passe", irei anexar a imagem.

![screenshot_2018-12-27-16-57-26-207_lockscreen](https://user-images.githubusercontent.com/39476953/50491449-93a3c100-09f9-11e9-9097-6ab77c3de00d.png)

Conforme eu for encontrando outras inconsistências irei reportar

**Comment by Feurrado** [comment]
devidamente corrigido, deverá sair após a 8.12.27, obrigado por reportar, fiquei uns meses sem traduzir por causa da faculdade mas agora voltarei, continue reportando ^^
