### ISSUE TITLE
Tradução Incorreta

### ISSUE THREAD

**Issue by xZezao** [ingbrzy/MA-XML-10-BRAZILIAN#21]
Segue em anexo outro texto que está em PT-PT e não PT-BR com as devidas correções

![screenshot_2018-12-27-17-12-16-069_lockscreen](https://user-images.githubusercontent.com/39476953/50491689-bd111c80-09fa-11e9-9515-91d95e6167fd.png)

**Comment by Feurrado** [comment]
Devidamente corrigido, deve sair após a 8.12.27

**Comment by zezao123** [comment]
Muito bom Feurrado, irei reportar sim sempre que puder, alias já criei até um novo issue, caso tenha algum tutorial sobre como fazer as modificações ao inves de ficar tirando print com os textos creio que seria de grande ajuda alem de não lhe incomodar mais haha
