### ISSUE TITLE
Faltando Traduções / Traduções Incorretas

### ISSUE THREAD

**Issue by zezao123** [ingbrzy/MA-XML-10-BRAZILIAN#25]
Irei tentar toda semana que sair um update checar se houve mudanças nas atualizações, se ainda existem traduções incorretas, misturando PT-PT e PT-BR ou se estão em inglês ainda, tambem irei atualizar traduzir quando lançarem novos recursos, irei anexar tudo que notei neste post, caso seja melhor visualizado cada um em uma ISSUE por favor de um reply informando. Segue os erros encontrados, já com suas devidas correções e traduções nas imagens:

![screenshot_2019-01-04-13-33-10-983_com android server telecom](https://user-images.githubusercontent.com/37622166/50703284-c0c82300-103a-11e9-9a1a-ea106090693f.png)
![screenshot_2019-01-04-15-47-16-674_com miui home](https://user-images.githubusercontent.com/37622166/50703286-c0c82300-103a-11e9-8a55-a541a17542b9.png)
![screenshot_2019-01-04-15-48-06-416_com android settings](https://user-images.githubusercontent.com/37622166/50703287-c0c82300-103a-11e9-876a-e40ab82351ab.png)
![screenshot_2019-01-04-15-50-56-599_com android settings](https://user-images.githubusercontent.com/37622166/50703288-c160b980-103a-11e9-89d5-01ef44910f3c.png)
![screenshot_2019-01-04-15-53-23-849_com android settings](https://user-images.githubusercontent.com/37622166/50703290-c160b980-103a-11e9-956e-247a1ccb1145.png)
![screenshot_2019-01-04-15-53-26-071_com android settings](https://user-images.githubusercontent.com/37622166/50703291-c1f95000-103a-11e9-8d1d-352b4da91e1e.png)
![screenshot_2019-01-04-15-55-27-931_com android settings](https://user-images.githubusercontent.com/37622166/50703292-c1f95000-103a-11e9-98e3-33af64ee052c.png)

**Comment by Feurrado** [comment]
Todas as linhas devidamente corrigidas, espere sair na próxima att; novamente agradeço a ajuda com as traduções, infelizmente não estou com muito tempo para traduzir mas faço o possível.
