### ISSUE TITLE
Tradução incorreta

### ISSUE THREAD

**Issue by zezao123** [ingbrzy/MA-XML-10-BRAZILIAN#26]
Não sei como isto passou batido por tanto tempo kk

![screenshot_2019-01-10-08-47-58-719_com android settings](https://user-images.githubusercontent.com/37622166/50987111-ca94cf00-14ef-11e9-8dd0-e4422fddd929.png)

**Comment by Feurrado** [comment]
KKKKK, infelizmente foi minha culpa por falta de tempo, peço perdão.
