### ISSUE TITLE
Erros de Tradução/Configurações

### ISSUE THREAD

**Issue by rodrigovet** [ingbrzy/MA-XML-10-BRAZILIAN#30]
![1](https://user-images.githubusercontent.com/30162760/51443065-f1f75300-1cca-11e9-8dae-fec22ef2aaf2.png)

![2](https://user-images.githubusercontent.com/30162760/51443069-fae82480-1cca-11e9-92c9-dede15c3eb7d.png)

![acessibilidade](https://user-images.githubusercontent.com/30162760/51443074-03405f80-1ccb-11e9-877f-a32809817e9d.png)

![privacidade](https://user-images.githubusercontent.com/30162760/51443082-0a676d80-1ccb-11e9-8cd9-1fe298dfdbcd.png)

**Comment by RicardoGuariento** [comment]
Rodrigo, pelo que verifiquei aqui, todas essas linhas já estão traduzidas na MIUI 10.3 Weekly.
