### ISSUE TITLE
Erros Tradução/Navegador

### ISSUE THREAD

**Issue by rodrigovet** [ingbrzy/MA-XML-10-BRAZILIAN#31]
![browser](https://user-images.githubusercontent.com/30162760/51443128-616d4280-1ccb-11e9-851a-a45238b7e9c6.png)

![browser 2](https://user-images.githubusercontent.com/30162760/51443133-692ce700-1ccb-11e9-83f9-7eb1e1ba93e8.png)

![browser 3](https://user-images.githubusercontent.com/30162760/51443136-70ec8b80-1ccb-11e9-8b62-9d54dde6ec85.png)

![browser 4](https://user-images.githubusercontent.com/30162760/51443139-777b0300-1ccb-11e9-961a-3100bdf8f642.png)

![browser 5](https://user-images.githubusercontent.com/30162760/51443142-7e097a80-1ccb-11e9-82d3-970764771796.png)

**Comment by RicardoGuariento** [comment]
Rodrigo, infelizmente a versão 10.2 Stable não recebe as atualizações de tradução. Neste caso, você precisa usar a Weekly para ver as traduções corrigidas.
