### ISSUE TITLE
Texto diferente

### ISSUE THREAD

**Issue by zezao123** [ingbrzy/MA-XML-10-BRAZILIAN#33]
Um ta minúsculo e outro minúsculo, tem que manter um padrão, melhor tudo maiúsculas não?

**Comment by zezao123** [comment]
![screenshot_2019-03-04-01-31-24-208_lockscreen](https://user-images.githubusercontent.com/37622166/53710812-c1ecb500-3e1d-11e9-84e8-ec6d6bf8af79.png)

**Comment by maaxpane** [comment]
melhor tudo maiúsculo

**Comment by RicardoGuariento** [comment]
> Um ta minúsculo e outro minúsculo, tem que manter um padrão, melhor tudo maiúsculas não?

Infelizmente não consigo editar isso. Foi uma das primeiras coisas que vi quando instalei a ROM. No XML já está certinho, acredito que seja algo dentro do código que faz o "Emergência" ficar tudo em maísculo.

**Comment by KcNirvana** [comment]
@RicardoGuariento 
Boas,
Se puseres esta string:
<string name="phone_locked_foget_password_mehod_back">Voltar</string>
em maiúsculo a partida deve ficar tudo maiusculo
Abraço

**Comment by RicardoGuariento** [comment]
Oi boa noite!

Obrigado pela dica!

Uma dúvida: Por que eles não compilam o DocumentsUI?



Enviado do meu Mi A2
Em KcNirvana <notifications@github.com>, 14 de mar de 2019 19:53 escreveu:

@RicardoGuariento<https://github.com/RicardoGuariento>
Boas,
Se puseres esta string:
Voltar
em maiúsculo a partida deve ficar tudo maiusculo
Abraço

**Comment by RicardoGuariento** [comment]
Pronto! Fiz como o KcNirvana sugeriu. Vamos esperar a próxima build.
