### ISSUE TITLE
XML issues

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-10-BRAZILIAN#35]
https://translators.xiaomi.eu/XML_MIUI10-Brazilian-Portuguese-pt-rBR.html

fix it please.. 

thanks

**Comment by RicardoGuariento** [comment]
I fixed theses lines! 

Please, let me know if everythings is OK now!

**Comment by RicardoGuariento** [comment]
> https://translators.xiaomi.eu/XML_MIUI10-Brazilian-Portuguese-pt-rBR.html
> 
> fix it please..
> 
> thanks

I fixed theses lines!

Let me know if everything if OK now
